### ISSUE TITLE
Error in example: /libxtrx/examples/xtrx_fft 

### ISSUE THREAD

**Issue by kurtulmehtap** [xtrx-sdr/libxtrx#1]
We have a XTRX with PCIe Front end.
We got an error when running the xtrx_fft example: **ERROR:   Wire RX pkt size is 65536, should be rounded to 128 bit and less 32768**
Here is the output:
hp@hp:~/images/sources/build/libxtrx/examples/xtrx_fft$ sudo ./mainwindow
[sudo] password for hp:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
10:59:09.281316 INFO:    Probing 'libxtrxll_pcie.so.0' low-level library
10:59:09.281823 INFO:    Probing 'libxtrxll_libusb3380.so.0' low-level library
10:59:09.289444 ERROR:   USB3380: Unable to open USB3380!
10:59:09.289554 ERROR:   Unable to allocate USB3380 context: error: -6
10:59:09.289602 INFO:    XTRX PCI_9: XTRX Rev4 (04000013)
10:59:09.289611 INFO:    XTRX PCI_9: Device `/dev/xtrx0` was opened
CPU Features: SSE2+ SSE4.1+ AVX+ FMA+
10:59:09.289651 INFO:    LMS PMIC: DCDC out set to V18=1880mV V33=3100mV V14=1480mV V12=1340mV
10:59:09.289662 INFO:    FPGA V_IO set to 1800mV
10:59:09.292355 WARNING: NLMS7 PCI_9: LMS VER:7 REV:1 MASK:1 (3841)
10:59:09.292397 INFO:    Starting XTRX debug thread
10:59:09.332980 INFO:    xtrx_set_samplerate: set RefClk to 26000000 based on 26060223 measurement
10:59:09.333024 WARNING: NLMS7 PCI_9: CGEN: VCO/2=1184000000 k/2=37 int=91 frac=80659
10:59:09.333567 WARNING: NLMS7 PCI_9: CGEN: binary result: 157
10:59:09.333935 WARNING: NLMS7 PCI_9: CGEN: Retuned [158:164] -> 161
10:59:09.334146 INFO:    FPGA V_IO set to 1800mV
10:59:09.334152 INFO:    xtrx_set_samplerate: rxrate=4,000MHz txrate=0,000MHz actual_master=32,000MHz rxdecim=2(h_1) txinterp=1(h_1) RX_ADC=8,000MHz TX_DAC=4,000MHz hintr=0 hdecim=0 delay=0 NRXFWD=0 LML1HID=3 LML2HID=1 RX_div=0 TX_div=0 RX_TSP_div=1 TX_TSP_div=1 FclkRX=0,000 (PHS=0) RXx2=0
10:59:09.334171 INFO:    DC START
10:59:09.334224 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334241 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334259 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334278 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334303 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334319 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334340 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334362 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334379 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334396 WARNING: NLMS7 PCI_9:  5c1=0000
10:59:09.334446 WARNING: NLMS7 PCI_9:  TX[0]=0000
10:59:09.334498 WARNING: NLMS7 PCI_9:  TX[1]=0000
10:59:09.334550 WARNING: NLMS7 PCI_9:  TX[2]=0000
10:59:09.334608 WARNING: NLMS7 PCI_9:  TX[3]=0000
10:59:09.334673 WARNING: NLMS7 PCI_9:  RX[0]=0000
10:59:09.334724 WARNING: NLMS7 PCI_9:  RX[1]=0000
10:59:09.334785 WARNING: NLMS7 PCI_9:  RX[2]=0000
10:59:09.334836 WARNING: NLMS7 PCI_9:  RX[3]=0000
10:59:09.334860 INFO:    FE_FREQ: rx=1 type=0 freq=100000000,000000 ch=3
10:59:09.334980 WARNING: NLMS7 PCI_9: SXR: initial VCO=3200000000 DIVH=5 VCOs:0110
10:59:09.334983 WARNING: NLMS7 PCI_9: SXX: VCO1 N=123 frac=80659
10:59:09.335317 WARNING: NLMS7 PCI_9: SXX: binary result: 255
10:59:09.335355 WARNING: NLMS7 PCI_9: SXR: VCO1 [0;0] -> 0
10:59:09.335357 WARNING: NLMS7 PCI_9: SXX: VCO2 N=123 frac=80659
10:59:09.335632 WARNING: NLMS7 PCI_9: SXX: binary result: 1
10:59:09.335655 WARNING: NLMS7 PCI_9: SXX: VCO1 N=123 frac=80659
10:59:09.335829 WARNING: NLMS7 PCI_9: SXX: binary result: 255
10:59:09.335851 WARNING: NLMS7 PCI_9: SXR: VCO1 [0;0] -> 0
10:59:09.335852 WARNING: NLMS7 PCI_9: SXX: VCO2 N=123 frac=80659
10:59:09.336026 WARNING: NLMS7 PCI_9: SXX: binary result: 1
10:59:09.336071 WARNING: NLMS7 PCI_9: 0x0124[18, 00]
10:59:09.336144 WARNING: NLMS7 PCI_9: TIA: CCOMP=15 CFB=3350 RCOMP=0
10:59:09.336220 INFO:    Set gain 15,0 to 0 on 1 channel
10:59:09.336224 WARNING: NLMS7 PCI_9: RFE: set_lna(15 -> 15) => 6
10:59:09.336303 INFO:    AFE: TX=[0;0] RX=[1;0]
10:59:09.336359 WARNING: NLMS7 PCI_9: 0x0124[1c, 00]
10:59:09.336474 INFO:    RBB: Restore BW[0]=500000
10:59:09.336477 WARNING: NLMS7 PCI_9: TIA: CCOMP=15 CFB=3350 RCOMP=0
10:59:09.336554 **ERROR:   Wire RX pkt size is 65536, should be rounded to 128 bit and less 32768**
10:59:09.336571 WARNING: NLMS7 PCI_9: 0x0124[18, 00]
10:59:09.337909 INFO:    XTRX PCI_9: Device closing

**Comment by sergforce** [comment]
update to master
