### ISSUE TITLE
xtrx gr-osmosdr fork breaks due to xtrx_open_list() removal

### ISSUE THREAD

**Issue by lainy** [xtrx-sdr/libxtrx#10]
[This commit](https://github.com/xtrx-sdr/libxtrx/commit/4f1eb7b5f77c90bc8d0db2a17fe338372e3d4277#diff-c52ffa8e3abcf49f18a71b8807b30dd9L435) replaces `xtrx_open_list` with `xtrx_open_string`, breaking gr-osmosdr build due to this line:
https://github.com/xtrx-sdr/gr-osmosdr/blob/libxtrx/lib/xtrx/xtrx_obj.cc#L71

**Comment by bkerler** [comment]
I can also confirm that issue. Looks like the changes broke gr-osmosdr.

**Comment by lainy** [comment]
I've created a [pull request](https://github.com/xtrx-sdr/gr-osmosdr/pull/2) over at the xtrx fork of gr-osmosdr that solves this.

**Comment by chemeris** [comment]
The PR is merged.
