### ISSUE TITLE
Failed to build libxtrx - ‘XTRXLL_PARAM_EXT_SPI’ undeclared

### ISSUE THREAD

**Issue by yahoo2016** [xtrx-sdr/libxtrx#11]
I got errors when tried to build libxtrx:

home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c: In function ‘adf4355_spi’:
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:88:30: error: ‘XTRXLL_PARAM_EXT_SPI’ undeclared (first use in this function)
  res = xtrxll_set_param(dev, XTRXLL_PARAM_EXT_SPI, MAKE_OCTO_SPI(REG_TMP_L, out));
                              ^
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:88:30: note: each undeclared identifier is reported only once for each function it appears in
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c: In function ‘trf37_spi’:
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:144:30: error: ‘XTRXLL_PARAM_EXT_SPI’ undeclared (first use in this function)
  res = xtrxll_set_param(dev, XTRXLL_PARAM_EXT_SPI, MAKE_OCTO_SPI(REG_TMP_L, out));
                              ^
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c: In function ‘octo_read_spi’:
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:159:34: error: ‘XTRXLL_PARAM_EXT_SPI’ undeclared (first use in this function)
  int res = xtrxll_set_param(dev, XTRXLL_PARAM_EXT_SPI, MAKE_OCTO_SPI(regno, 0));
                                  ^
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:165:32: error: ‘XTRXLL_EXT_SPI_RB’ undeclared (first use in this function)
  return xtrxll_get_sensor(dev, XTRXLL_EXT_SPI_RB, (int*)out);
                                ^
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c: In function ‘i2c_cmdwr’:
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:183:30: error: ‘XTRXLL_PARAM_EXT_SPI’ undeclared (first use in this function)
  res = xtrxll_set_param(dev, XTRXLL_PARAM_EXT_SPI,
                              ^
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c: In function ‘lms7octo_init’:
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:438:33: error: ‘XTRXLL_PARAM_EXT_SPI’ undeclared (first use in this function)
   res = xtrxll_set_param(lldev, XTRXLL_PARAM_EXT_SPI,
                                 ^
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c: In function ‘lms7octo_deinit’:
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:501:39: error: ‘XTRXLL_PARAM_EXT_SPI’ undeclared (first use in this function)
   res = xtrxll_set_param(dev->master, XTRXLL_PARAM_EXT_SPI,
                                       ^
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c: In function ‘octo_switch_fe’:
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:530:48: error: ‘XTRXLL_PARAM_EXT_SPI’ undeclared (first use in this function)
    r = (r) ? r : xtrxll_set_param(dev->master, XTRXLL_PARAM_EXT_SPI,
                                                ^
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:537:17: warning: implicit declaration of function ‘lms7_rbb_set_ext’ [-Wimplicit-function-declaration]
   r = (r) ? r : lms7_rbb_set_ext(&dev->lms->lms_state);
                 ^
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c: In function ‘lms7octo_dd_set_modes’:
/home/nvidia/xtrx/images/sources/libxtrx/xtrx_fe_octorx0.c:666:35: error: ‘XTRXLL_PARAM_EXT_SPI’ undeclared (first use in this function)
     xtrxll_set_param(dev->master, XTRXLL_PARAM_EXT_SPI,

**Comment by sergforce** [comment]
Have you update libxtrxll subrepo?

**Comment by yahoo2016** [comment]
Sergforce,

I'm not sure how to update libxtrxll subrepo.

https://github.com/xtrx-sdr/images

I did "git submodule init & git submodule update" in "./images",  "./images/sources/libxtrx" and "./images/sources/libxtrxll", but the could not get the latest libxtrx and libxtrxll.
What are the steps to include the latest libxtrx and libxtrxll to the source tree of "https://github.com/xtrx-sdr/images"?

Thanks

**Comment by sergforce** [comment]
go to libxtrxll and pull changes manually. I'll fix the default links

% cd libxtrxll; git pull

**Comment by yahoo2016** [comment]
serforce,
Thanks for your quick response, I tried "git pull" in "images/sources/libxtrxll" but was asked for "<remote> <branch>", see below.  What <remote> <branch> should I use after "git pull"?

nvidia@tegra-ubuntu:~/xtrx/images/sources/libxtrxll$ git pull
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

**Comment by yahoo2016** [comment]
"git submodule init" and "git submodule update"  only pull old libs.
I had to remove all old libs and manually clone new libs under "images/sources"
