### ISSUE TITLE
Anyone running gnuradio or gr-osmocom/Soapy app (gqrx, pothos)?

### ISSUE THREAD

**Issue by OhSoGood** [xtrx-sdr/libxtrx#28]
Hi
Has anyonye manage to make the xtrx work correctly with any usual app like gnuradio, pothos, gqrx, etc, actually any Soapy or gr-osmocom app ?

I have been using many brands of SDR but I must say the XTRX is the first one miserably failing whatever I do - using prebuilt binaries (which show several issues) or compiling them - and I'm not even speaking of hardware failure that I had with the 1st card board (replaced since). The must I managed was to get working soapy app but the spectrum I get are all flat. On the very same computers (running Linux Mint or Ubuntu 18.04), USRP, LimeSdr and BladeRF are just running fine.

And the total lack of support by the XTRX team at Fairwaves is simply astounding, whether on github, by email or by telegram.

If anybody was nice to give working instructions, I would appreciate so much, as on paper the card looks promising (and I keep hoping the XTRX is not a hoax).

**Comment by hewittc** [comment]
Using SoapySDR + Pothos framework here and I can only stream RX with the patch I provided in https://github.com/xtrx-sdr/libxtrx/issues/27. I built everything from source.

**Comment by OhSoGood** [comment]
@hewittc : Thank you, the patch was welcome. Despite this, with both gnuradio (using osmocom) and pothos (with soapy), I get a flat white-noise only spectrum. I wonder if my card could be defective, or if I make a stupid mistake while setting the xtrx params. Could you send me a simple pothos or GRC file to listen say on the wifi 2.4 band that you have tested on your PC ?

**Comment by arsalantheoffice** [comment]
Hi, I am using xtrx with PCIe adapter. It was working well by compiling the sources of all the libraries. I have also tested it with osmosdr in gnuradio using Soapy libraries and also with xtrx libraries. Made our own OOT module for gnuradio. I am also stuck with the problem that you are facing but it arise when I installed libosmocore and I don't know yet how it's linked or may be some other thing caused this issue. Before that most of things were working fine.
Main point is that the flat white noise spectrum is because of the dependent libraries, settings of xtrx and some other software issue. And at the same time LimeSDR is working fine on this PC.

**Comment by OhSoGood** [comment]
@arsalantheoffice : did you see the email I sent you Tuesday 28/7 ?

**Comment by OhSoGood** [comment]
@arsalantheoffice  : Did you find the issue with the XTRX with the PCIe adapter? Was it libosmocore the culprit? I've left alone the card in the meantime and am getting back to it these days.

**Comment by arsalantheoffice** [comment]
> @arsalantheoffice : did you see the email I sent you Tuesday 28/7 (on your gmail account)?

No, I have not received any Email.


> @arsalantheoffice : Did you find the issue with the XTRX with the PCIe adapter? Was it libosmocore the culprit? I've left alone the card in the meantime and am getting back to it these days.

I tried to solve the issue for some time but couldn't make it work with PCIe Adapter. May be the front end of the pcie adapter have some fault or something. But I had installed two pcie adapters and both are not working. Both were working one day and next day both didn't work. I suspected that may be some software change is the culprit but I reverted everything and tried to make it work but all in vain. Now I am using the xtrx with octopack. xtrx are working fine without pcie adapters.

**Comment by RFNOD** [comment]
@OhSoGood The master branch of gr-osmosdr supports the XTRX. Give that a try.

**Comment by RFNOD** [comment]
@hewittc I reached out to a maintainer, he should be able to merge once he gets the PR.

**Comment by RFNOD** [comment]
https://git.osmocom.org/gr-osmosdr/commit/?id=dc82ffd1f8b7fee5a8de2d73dabd24eb6d83d5a6

**Comment by earwin** [comment]
Thanks, @RFNOD 

Sorry folks, for the lack of support.
XTRX authors are for the time being not in position to work on it, hopefully this will change.
I have access to repositories, but not a lot of free time, so I can merge pull requests that don't take too much effort (and deep knowledge) to verify.
